# Generated by Django 5.2.3 on 2025-06-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_icon', models.CharField(max_length=50)),
                ('services_title', models.CharField(max_length=50)),
                ('services_des', models.TextField()),
            ],
        ),
    ]
