# Generated by Django 5.2.3 on 2025-07-11 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_login_form_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be exactly 14 digits', regex='^\\d{14}$')])),
                ('address', models.TextField(max_length=50, unique=True)),
                ('experience', models.IntegerField()),
                ('worksample', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('coordinates', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
