# Generated by Django 5.2.3 on 2025-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviceprovider_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='worksample',
            field=models.ImageField(upload_to='worksamples/'),
        ),
    ]
