# Generated by Django 5.2 on 2025-08-06 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_serviceprovider_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be exactly 14 digits', regex='^\\d{14}$')])),
                ('address', models.TextField(max_length=50, unique=True)),
                ('experience', models.IntegerField()),
                ('worksample', models.ImageField(upload_to='worksamples/')),
                ('coordinates', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.AddField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AlterUniqueTogether(
            name='providerservice',
            unique_together={('provider', 'service')},
        ),
    ]
