# Generated by Django 5.2 on 2025-08-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_provider_providerservice_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_form',
        ),
    ]
